name = "CPUSummary"
uuid = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Hwloc = "2"
IfElse = "0.1"
Static = "0.2"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
